name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      deploy_target:
        description: 'Component to deploy'
        required: true
        default: 'thinking'
        type: choice
        options:
          - thinking
          - proxy
          - both
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  deploy-thinking:
    runs-on: ubuntu-latest
    if: inputs.deploy_target == 'thinking' || inputs.deploy_target == 'both'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
      
      # Try to download the latest artifacts from the build workflow
      - name: Download backend package
        id: download-backend
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: backend-package
          path: .
          
      - name: Download frontend package
        id: download-frontend
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: frontend-package
          path: .
          
      # Build backend if artifact not found
      - name: Build backend (fallback)
        if: steps.download-backend.outcome != 'success' || steps.download-frontend.outcome != 'success'
        run: |
          echo "Artifacts not found. Building packages locally..."
          
          # Backend setup
          python -m pip install --upgrade pip
          pip install uv
          uv venv .venv
          uv pip install -r backend/requirements.txt
          
          # Frontend setup
          cd frontend
          npm install --no-package-lock
          npm install rehype-raw@7.0.0 --save
          NODE_ENV=production npm run build
          cd ..
          
          # Package files for deployment
          tar -czf backend.tar.gz backend
          tar -czf frontend.tar.gz frontend/dist
          
          echo "Build complete. Packages ready for deployment."

      # Deploy to server
      - name: Transfer files to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: deploy
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: "backend.tar.gz,frontend.tar.gz"
          target: "/home/deploy"
          overwrite: true
          
      # Deploy on server
      - name: Deploy Thinking application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: deploy
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            # Set up deployment directories
            mkdir -p /home/deploy/deploy_new/backend /home/deploy/deploy_new/frontend/dist
            
            # Extract files
            cd /home/deploy
            tar -xzf backend.tar.gz -C /home/deploy/deploy_new
            tar -xzf frontend.tar.gz -C /home/deploy/deploy_new
            rm backend.tar.gz frontend.tar.gz
            
            # Backup .env file if it exists
            if [ -f /home/thinking/thinking/backend/.env ]; then
                cp /home/thinking/thinking/backend/.env /home/deploy/backend.env.backup
            fi
            
            # Clean target directories (excluding .env.backup)
            sudo find /home/thinking/thinking/backend -mindepth 1 -not -name '.env.backup' -delete 2>/dev/null || true
            sudo find /home/thinking/thinking/frontend/dist -mindepth 1 -delete 2>/dev/null || true
            
            # Deploy files
            sudo cp -r /home/deploy/deploy_new/backend/* /home/thinking/thinking/backend/ 2>/dev/null || true
            sudo cp -r /home/deploy/deploy_new/frontend/dist/* /home/thinking/thinking/frontend/dist/ 2>/dev/null || true
            
            # Restore .env file if backup exists
            if [ -f /home/deploy/backend.env.backup ]; then
                sudo cp /home/deploy/backend.env.backup /home/thinking/thinking/backend/.env
                rm /home/deploy/backend.env.backup
            fi
            
            # Verify environment variables in .env file
            echo "Verifying required environment variables..."
            required_vars=("OPENAI_API_KEY" "OPENAI_API_URL" "OPENAI_MODEL" 
                          "GROK_API_KEY" "GROK_API_URL" "GROK_MODEL" 
                          "QWEN_API_KEY" "QWEN_API_URL" "QWEN_MODEL" 
                          "DEEPSEEK_API_KEY" "DEEPSEEK_API_URL" "DEEPSEEK_MODEL" 
                          "GLM_API_KEY" "GLM_API_URL" "GLM_MODEL" 
                          "DOUBAO_API_KEY" "DOUBAO_API_URL" "DOUBAO_MODEL")
            
            for var in "${required_vars[@]}"; do
              if ! grep -q "^$var=" /home/thinking/thinking/backend/.env; then
                echo "Warning: $var is missing from .env file"
              fi
            done
            
            # Fix permissions after deployment
            sudo chown -R nginx:nginx /home/thinking/thinking/frontend/dist
            sudo chmod -R 755 /home/thinking/thinking/frontend/dist
            
            # Clean up
            rm -rf /home/deploy/deploy_new
            
            # Restart services automatically
            sudo systemctl restart thinking-backend
            sudo systemctl reload nginx
            
            echo "Thinking deployment complete. Services have been automatically restarted."
            
  deploy-proxy:
    runs-on: ubuntu-latest
    if: inputs.deploy_target == 'proxy' || inputs.deploy_target == 'both'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
      
      # Try to download the latest proxy artifacts
      - name: Download proxy package
        id: download-proxy
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: proxy-package
          path: .
      
      # Package proxy files if no artifact found
      - name: Build and package proxy files (fallback)
        if: steps.download-proxy.outcome != 'success'
        run: |
          echo "Proxy artifact not found. Building locally..."
          
          # Install proxy dependencies
          cd proxy
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
          # Run any tests if needed
          if [ -d "tests" ]; then
            echo "Running proxy tests..."
            pytest || echo "Tests failed but continuing with deployment"
          fi
          
          cd ..
          
          # Package proxy files
          tar -czf proxy.tar.gz proxy
          
          echo "Proxy build complete. Package ready for deployment."
      
      # Deploy to server
      - name: Transfer proxy files to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: deploy
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: "proxy.tar.gz"
          target: "/home/deploy"
          overwrite: true
          
      # Deploy proxy on server
      - name: Deploy Proxy service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: deploy
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            # Set up deployment directories
            mkdir -p /home/deploy/deploy_new/proxy
            
            # Extract files
            cd /home/deploy
            tar -xzf proxy.tar.gz -C /home/deploy/deploy_new
            rm proxy.tar.gz
            
            # Backup proxy .env file if it exists
            if [ -f /home/thinking/proxy/.env ]; then
                cp /home/thinking/proxy/.env /home/deploy/proxy.env.backup
            fi
            
            # Clean target directory
            sudo find /home/thinking/proxy -mindepth 1 -not -name '.env.backup' -delete 2>/dev/null || true
            
            # Deploy files
            sudo cp -r /home/deploy/deploy_new/proxy/* /home/thinking/proxy/ 2>/dev/null || true
            
            # Restore .env file if backup exists
            if [ -f /home/deploy/proxy.env.backup ]; then
                sudo cp /home/deploy/proxy.env.backup /home/thinking/proxy/.env
                rm /home/deploy/proxy.env.backup
            fi
            
            # Clean up
            rm -rf /home/deploy/deploy_new
            
            # Restart proxy service
            sudo systemctl restart thinking-proxy
            
            echo "Proxy deployment complete. Service has been automatically restarted."
