name: Proxy CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'proxy/**'
      - '.github/workflows/proxy-cicd.yml'
  workflow_dispatch:
  pull_request:
    paths:
      - 'proxy/**'
      - '.github/workflows/proxy-cicd.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: proxy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Run tests (if any)
        run: |
          if [ -d "tests" ]; then pytest; else echo "No tests directory, skipping tests."; fi

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_PROXY_SSH_KEY }}
      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.DEPLOY_PROXY_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy to server as deploy user
        env:
          DEPLOY_PROXY_HOST: ${{ secrets.DEPLOY_PROXY_HOST }}
          DEPLOY_PROXY_USER: deploy
        run: |
          ssh -o StrictHostKeyChecking=no $DEPLOY_PROXY_USER@$DEPLOY_PROXY_HOST 'mkdir -p ~/thinking/proxy'
          scp -r proxy/* $DEPLOY_PROXY_USER@$DEPLOY_PROXY_HOST:~/thinking/proxy/
          ssh -o StrictHostKeyChecking=no $DEPLOY_PROXY_USER@$DEPLOY_PROXY_HOST '
            cd ~/thinking/proxy &&
            if [ ! -d "../../.venv" ]; then
              echo "Creating Python virtual environment..."
              mkdir -p ../../.venv
              # Try to use uv if available or install it
              if ! command -v uv &> /dev/null; then
                echo "Installing uv..."
                pip install uv || {
                  echo "Failed to install uv, falling back to venv"
                  python3 -m venv ../../.venv
                }
              else
                python3 -m uv venv ../../.venv
              fi
            fi &&
            source ../../.venv/bin/activate &&
            # Use uv for pip if available, otherwise use regular pip
            if command -v uv &> /dev/null; then
              python3 -m uv pip install -r requirements.txt
            else
              pip install -r requirements.txt
            fi &&
            bash bin/restart.sh
          '
