name: Proxy CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'proxy/**'
      - '.github/workflows/proxy-cicd.yml'
  workflow_dispatch:
  pull_request:
    paths:
      - 'proxy/**'
      - '.github/workflows/proxy-cicd.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: proxy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Run tests (if any)
        run: |
          if [ -d "tests" ]; then pytest; else echo "No tests directory, skipping tests."; fi
