name: Thinking CICD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Backend: Build and test
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install uv and dependencies
        run: |
          pip install uv
          uv venv .venv
          uv pip install -r backend/requirements.txt
      - name: Run backend tests
        run: |
          source .venv/bin/activate
          PYTHONPATH=$PYTHONPATH:$(pwd) pytest backend/tests --maxfail=1 --disable-warnings

      # Frontend: Build
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Debug frontend dependencies
        run: |
          cd frontend
          echo "Current directory: $(pwd)"
          echo "Package.json content:"
          cat package.json
          echo "\n\n"
      - name: Install frontend dependencies
        run: |
          cd frontend
          rm -rf node_modules
          npm install --no-package-lock
          npm install rehype-raw@7.0.0 --save
          npm list rehype-raw
      - name: Build frontend
        run: |
          cd frontend
          NODE_ENV=production npm run build
      - name: Upload frontend build
        uses: actions/upload-pages-artifact@v3
        with:
          name: frontend-dist
          path: frontend/dist

  # Upload artifacts for later deployment
  upload-artifacts:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Get frontend build from previous job
      - name: Download frontend build
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist
      - name: Extract frontend artifact
        run: |
          cd frontend/dist
          tar -xf artifact.tar
          rm artifact.tar

      # Prepare deployment packages
      - name: Package files for deployment
        run: |
          tar -czf backend.tar.gz backend
          tar -czf frontend.tar.gz frontend/dist
      
      # Upload deployment packages as artifacts
      - name: Upload backend package
        uses: actions/upload-artifact@v4
        with:
          name: backend-package
          path: backend.tar.gz
          retention-days: 5
      
      - name: Upload frontend package
        uses: actions/upload-artifact@v4
        with:
          name: frontend-package
          path: frontend.tar.gz
          retention-days: 5
